<script lang="ts" setup>
import { ChevronDown, ChevronUp, Sun, Moon, SunMoon, Menu, ExternalLink, ChevronRight, Search } from "lucide-vue-next";
import {navigationMenuTriggerStyle} from "~/components/ui/navigation-menu";

const router = useRouter();
const route = useRoute();
const colorMode = useColorMode();

const externalLinks: {title: string; url: string}[] = [
// 	{
// 		title: "IDN",
// 		url: "https://mspgh.unimelb.edu.au/centres-institutes/onemda/research-group/indigenous-studies-unit/indigenous-data-network",
// 	}
    {
        title: "The National Indigenous Data Catalogue",
        url: "https://data.idnau.org/"
    }
 ];

const navigation = [
    {
        "title": "Home",
        "path": "https://idnau.org/",
        "stem": "1.index",
        "description": "",
        "websiteURL": "https://idnau.org/"
    },
    {
        "title": "About",
        "path": "/about",
        "stem": "2.about/1.index",
        "children": [
            {
                "title": "About",
                "path": "/about",
                "stem": "2.about/1.index",
                "description": "",
                "websiteURL": "https://idnau.org/idc"
            },
            {
                "title": "About the Indigenous Data Commons",
                "path": "/about/about-the-commons",
                "stem": "2.about/2.about-the-commons",
                "description": "The Indigenous Data Commons is an online platform that provides Aboriginal and Torres Strait Islander communities with the necessary infrastructure to find, record and describe Indigenous data while supporting Indigenous Peoples' rights and interests, and authority to control their data. The Indigenous Data Network defines Indigenous data as all data generated by, about, or for Aboriginal and Torres Strait Islander people in Australia. Indigenous research data specifically refers to information that is collected, analysed, and interpreted within the context of Indigenous communities, cultures, and knowledge systems. It includes data gathered through research projects conducted by and with Indigenous peoples, as well as data that Indigenous communities have generated and maintained themselves. Indigenous data includes traditional ecological knowledge, oral histories, cultural practices, and other forms of Indigenous knowledge.",
                "websiteURL": "https://idnau.org/about/about-the-commons"
            },
            {
                "title": "Partners & Collaborators",
                "path": "/about/partners-and-collaborators",
                "stem": "2.about/3.partners-and-collaborators",
                "description": "The IDN partners with a wide range of Aboriginal community-controlled organisations, universities, Indigenous businesses, government agencies and data authorities. Link to websites",
                "websiteURL": "https://idnau.org/about/partners-and-collaborators"
            },
            {
                "title": "FAQ",
                "path": "/about/faq",
                "stem": "2.about/4.faq",
                "description": "Frequently Asked Questions",
                "websiteURL": "https://idnau.org/about/faq"
            },
            {
                "title": "Contact Us",
                "path": "/about/contact",
                "stem": "2.about/5.contact",
                "description": "Find out more about the work of the Indigenous Data Network at the Indigenous Studies Unit website. For more information about the Indigenous Data Network please contact data-indigenous@unimelb.edu.au.",
                "websiteURL": "https://idnau.org/about/contact"
            },
            {
                "title": "IDC Newsletter",
                "path": "/about/newsletter",
                "stem": "2.about/6.newsletter",
                "description": "Sign up for the Indigenous Data Commons newsletter",
                "websiteURL": "https://idnau.org/about/newsletter"
            },
            {
                "title": "Events",
                "path": "/about/events",
                "stem": "2.about/7.events",
                "description": "Stay tuned to our upcoming events",
                "websiteURL": "https://idnau.org/about/events"
            },
            {
                "title": "IDN",
                "path": "/about/idn",
                "stem": "2.about/8.idn",
                "description": "",
                "websiteURL": "https://mspgh.unimelb.edu.au/centres-institutes/onemda/research-group/indigenous-studies-unit/indigenous-data-network"
            }
        ],
        "description": "",
        "websiteURL": "https://idnau.org/about"
    },
    {
        "title": "Resources",
        "path": "/resources",
        "stem": "3.resources/1.index",
        "children": [
            {
                "title": "Resources",
                "path": "/resources",
                "stem": "3.resources/1.index",
                "description": "",
                "websiteURL": "https://idnau.org/resources"
            },
            {
                "title": "IDN Catalogue Profile",
                "path": "/resources/idn-catalogue-profile",
                "stem": "3.resources/2.idn-catalogue-profile",
                "description": "",
                "websiteURL": "https://idn-au.github.io/idn-catalogue-profile/profile.html"
            },
            {
                "title": "IDN Metadata Profile",
                "path": "/resources/idn-metadata-profile",
                "stem": "3.resources/3.idn-metadata-profile",
                "description": "",
                "websiteURL": "https://idn-au.github.io/idn-catalogue-profile/resources/guidance.html"
            },
            {
                "title": "Key Principles",
                "path": "/resources/key-principles",
                "stem": "3.resources/4.key-principles",
                "description": "",
                "websiteURL": "https://idnau.org/resources/key-principles"
            },
            {
                "title": "Publications",
                "path": "/resources/publication",
                "stem": "3.resources/5.publication",
                "description": "",
                "websiteURL": "https://idnau.org/resources/publications"
            },
            {
                "title": "Glossary",
                "path": "/resources/glossary",
                "stem": "3.resources/6.glossary",
                "description": "",
                "websiteURL": "https://idnau.org/resources/glossary"
            },
            {
                "title": "How-to Guides",
                "path": "/resources/how-to-guides",
                "stem": "3.resources/7.how-to-guides",
                "description": "",
                "websiteURL": "https://idnau.org/resources/how-to-guides"
            }
        ],
        "description": "",
        "websiteURL": "https://idnau.org/resources"
    },
    {
        "title": "Tools",
        "path": "/tools",
        "stem": "4.tools/1.index",
        "children": [
            {
                "title": "Tools",
                "path": "/tools",
                "stem": "4.tools/1.index",
                "description": "",
                "websiteURL": "https://idnau.org/tools"
            },
            {
                "title": "Map Search",
                "path": "/tools/map-search",
                "stem": "4.tools/2.map-search",
                "description": "",
                "websiteURL": "https://idnau.org/resources/map"
            },
            {
                "title": "Agent Database",
                "path": "/tools/agent-database",
                "stem": "4.tools/3.agent-database",
                "description": "",
                "websiteURL": "https://agentsdb.idnau.org"
            },
            {
                "title": "Metadata Entry Tools",
                "path": "/tools/metadata-entry-tool",
                "stem": "4.tools/4.metadata-entry-tool",
                "description": "",
                "websiteURL": "https://metadata.idnau.org/"
            }
        ],
        "description": "",
        "websiteURL": "https://idnau.org/tools"
    }
]


const showSidenav = ref(false);

router.beforeEach((to, from) => {
    showSidenav.value = false;
});
</script>

<template>
    <header class="top-nav sticky top-0 bg-background/40 grid grid-cols-2 md:flex md:flex-row md:justify-between items-center p-2 z-50 gap-2 backdrop-sm backdrop-blur-sm">
        <!-- mobile nav -->
        <Sheet v-model:open="showSidenav">
            <SheetTrigger asChild>
                <Button variant="ghost" size="icon" class="md:flex">
                    <Menu class="size-8" />
                </Button>
            </SheetTrigger>
            <SheetContent side="left" class="p-2 w-84" hideClose>
                <SheetHeader class="grid grid-cols-3 gap-2 mb-4">
                    <SheetClose asChild>
                        <Button variant="ghost" size="icon">
                            <Menu class="size-4" />
                        </Button>
                    </SheetClose>
                    <NuxtLink to="/">
                        <div class="flex flex-col gap-3 items-center justify-center">                            
                            <NuxtImg v-show="colorMode.unknown || colorMode.value === 'light'" src="/apple-touch-icon.png" alt="The Indigenous Data Commons Logo" class="h-[40px]" />
                            <NuxtImg v-show="!colorMode.unknown && colorMode.value === 'dark'" src="/apple-touch-icon.png" alt="The Indigenous Data Commons Logo" class="h-[40px]" />
                            <!-- <span class="text-xs whitespace-nowrap">The Indigenous Data Commons</span> -->
                        </div>
                    </NuxtLink>
                </SheetHeader>
                <nav class="nav-sidebar flex flex-col gap-2">
                    <template v-for="link of navigation">
                        <Collapsible v-if="link.children && link.children.length > 1" :defaultOpen="route.path.startsWith(link.path)" v-slot="{ open }">
                            <CollapsibleTrigger :class="`rounded-none border-l-2 border-l-transparent ${route.path.startsWith(link.path) ? 'border-l-isu-red' : ''}`" asChild>
                                <Button variant="ghost" class="w-full">
                                    {{ link.children.find(c => c.path === link.path)?.title || link.title }} 
                                    <ChevronUp v-if="open" class="size-4" />
                                    <ChevronDown v-else class="size-4" />
                                </Button>
                            </CollapsibleTrigger>
                            <CollapsibleContent class="flex flex-col gap-2 bg-secondary/50 rounded">
                                <template v-if="link.children.find(c => c.path === link.path)">
                                    <Button variant="ghost" :class="`rounded-none border-l-2 border-l-transparent ${route.path === link.path ? 'border-l-isu-red' : ''}`" asChild>
                                        
                                    </Button>
                                </template>
                                <Separator />
                                <Button v-for="child in link.children" variant="ghost" :class="`rounded-none border-l-2 border-l-transparent ${route.path.startsWith(child.path) ? 'border-l-isu-red' : ''}`" asChild>
                                    <NuxtLink v-if="child.path !== link.path" :to="child.websiteURL || child.path">{{ child.title }} </NuxtLink>
                                </Button>
                            </CollapsibleContent>
                        </Collapsible>
                        <Button v-else variant="ghost" :class="`rounded-none border-l-2 border-l-transparent ${route.path.startsWith(link.path) ? 'border-l-isu-red' : ''}`" asChild>
                            <NuxtLink :to="link.websiteURL || link.path">{{ link.title }}</NuxtLink>
                        </Button>
                    </template>
                    <Button v-for="extLink in externalLinks" variant="ghost" asChild>
                        <a class="w-full flex justify-start items-center" :href="extLink.url" target="_blank" rel="noopener noreferrer">{{ extLink.title }} <ExternalLink class="size-4" /></a>
                    </Button>
                </nav>
            </SheetContent>
        </Sheet>
        <!-- <NuxtLink to="/">
            <div class="flex flex-row gap-2 items-center justify-center">
                <NuxtImg v-show="colorMode.unknown || colorMode.value === 'light'" src="/apple-touch-icon.png" alt="The Indigenous Data Commons Logo" class="h-[40px] md:h-[54px]" />
                <NuxtImg v-show="!colorMode.unknown && colorMode.value === 'dark'" src="/apple-touch-icon.png" alt="The Indigenous Data Commons Logo" class="h-[40px] md:h-[54px]" /> -->
                <!-- <span class="hidden md:inline text-xl">The Indigenous Data Commons</span> -->
                <!-- <span class="md:hidden text-xl">IDN</span> -->
            <!-- </div>
        </NuxtLink> -->
        <!-- desktop nav -->
       <!-- <nav class="ml-auto md:flex md:flex-row hidden">
           <template v-for="link of navigation">
               <DropdownMenu v-if="link.children && link.children.length > 1" v-slot="{open}">
                   <DropdownMenuTrigger asChild>
                       <Button variant="ghost" :class="`rounded-none p-2 border-b-2 border-b-transparent ${route.path.startsWith(link.path) ? 'border-b-isu-red' : ''}`">
                           {{ link.children.find(c => c.path === link.path)?.title || link.title }}
                           <ChevronUp v-if="open" class="size-4" />
                           <ChevronDown v-else class="size-4" />
                       </Button>
                   </DropdownMenuTrigger>
                   <DropdownMenuContent class="w-56 nav-dropdown">
                       <template v-if="link.children.find(c => c.path === link.path)">
                           <DropdownMenuItem :class="`rounded-none border-l-2 border-l-transparent ${route.path === link.path ? 'border-l-isu-red' : ''}`" asChild>
                               <NuxtLink :to="link.path" class="font-bold cursor-pointer">
                                   {{ link.children.find(c => c.path === link.path)?.title }} Home
                               </NuxtLink>
                           </DropdownMenuItem>
                           <DropdownMenuSeparator />
                       </template>
                       <DropdownMenuGroup>
                           <DropdownMenuItem v-for="child in link.children" :class="`rounded-none border-l-2 border-l-transparent ${route.path.startsWith(child.path) ? 'border-l-isu-red' : ''}`" asChild>
                               <NuxtLink v-if="child.path !== link.path" :to="child.path" class="cursor-pointer">{{ child.title }}</NuxtLink>
                           </DropdownMenuItem>
                       </DropdownMenuGroup>
                   </DropdownMenuContent>
               </DropdownMenu>
               <Button v-else variant="ghost" :class="`rounded-none p-2 border-b-2 border-b-transparent ${route.path.startsWith(link.path) ? 'border-b-isu-red' : ''}`" asChild>
                   <NuxtLink :to="link.path">{{ link.title }}</NuxtLink>
               </Button>
           </template>
           <Button v-for="extLink in externalLinks" variant="ghost" asChild>
               <a :href="extLink.url" target="_blank" rel="noopener noreferrer">{{ extLink.title }} <ExternalLink class="size-4" /></a>
           </Button>
       </nav> -->
        
        <div class="flex w-full flex-row justify-end items-center gap-2">
<!--             
                <Button variant="ghost" size="icon" title="Search the catalogue" as-child>
                    <NuxtLink to="/search"><Search /></NuxtLink>
                </Button> -->
            
	        <Button variant="ghost" size="icon" @click="!colorMode.unknown ? colorMode.value === 'dark' ? colorMode.preference = 'light' : colorMode.preference = 'dark' : undefined">
		        <SunMoon v-show="colorMode.unknown" />
		        <Sun v-show="colorMode.value === 'dark'" class="w-4 h-4" />
		        <Moon v-show="colorMode.value === 'light'" class="w-4 h-4" />
	        </Button>
        </div>
    </header>
</template>

