name: Build & deploy to Swift container

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  packages: read    # to access idn-lib GitHub NPM package

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20 # sass breaks with node v21
          cache: npm
          registry-url: "https://npm.pkg.github.com"
      - name: Install and build
        run: |
          npm ci
          CI=false npm run build
          cp dist/index.html dist/404error.html && cp dist/index.html dist/401error.html
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VITE_AGENT_NAMED_GRAPH: ${{ secrets.VITE_AGENT_NAMED_GRAPH }}
          VITE_TRIPLESTORE_URL: ${{ secrets.VITE_MRC_TRIPLESTORE_URL }}
      - name: Upload dist artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      OS_AUTH_URL: https://keystone.rc.nectar.org.au:5000/v3/
      OS_PROJECT_ID: 0a23562e67e04297b1dc3ce25a30858d
      OS_PROJECT_NAME: "unimelb-idc"
      OS_USER_DOMAIN_NAME: "Default"
      OS_PROJECT_DOMAIN_ID: "default"
      OS_USERNAME: "jamie.feiss@unimelb.edu.au"
      OS_PASSWORD: ${{ secrets.OS_PASSWORD }}
      OS_REGION_NAME: "Melbourne"
      OS_INTERFACE: public
      OS_IDENTITY_API_VERSION: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - name: Install OpenStack Swift CLI
        run: pip install python-swiftclient python-keystoneclient
      - name: Download dist artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist
      - name: Clear Swift container
        run: |
          objectList=$(swift list metadata_entry_tool)
          if [ ! -z "$objectList" ]
          then
          swift delete metadata_entry_tool $objectList
          fi
      - name: Upload to Swift container
        run: |
          cd dist
          swift upload metadata_entry_tool ./*
